GET http://localhost:3007/categories

###
POST http://localhost:3007/categories
Content-Type: application/json

{
    "name": "Movie"
}
###
PUT http://localhost:3007/categories/41550d8f-3f50-4801-bbeb-57b2ea9ee036
Content-Type: application/json

{
    "name": "Movie1111"
}
###
DELETE http://localhost:3007/categories/41550d8f-3f50-4801-bbeb-57b2ea9ee036
Content-Type: application/json

###
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 205
ETag: W/"cd-dnLeCsTF+e6xN4FdCnXaIK9FE04"
Date: Wed, 25 May 2022 21:21:33 GMT
Connection: close

{
  "items": [
    {
      "id": "b052f684-6b12-4642-8bc6-41249d776ffc",
      "name": "testing",
      "description": null,
      "is_active": true,
      "created_at": "2022-05-25T21:21:30.753Z"
    }
  ],
  "total": 1,
  "current_page": 1,
  "last_page": 1,
  "per_page": 15
}
