import { CategoriesController } from './categories.controller';
//import { Test, TestingModule } from '@nestjs/testing';
//import { CategoriesService } from './categories.service';

describe('CategoriesController Unit Tests', () => {
  let controller: CategoriesController;

  beforeEach(async () => {
    // original generated by Nest.js
    // const module: TestingModule = await Test.createTestingModule({
    //   controllers: [CategoriesController],
    //   providers: [CategoriesService],
    // }).compile();

    // controller = module.get<CategoriesController>(CategoriesController);

    controller = new CategoriesController();
  });

  // it('should be defined', () => {
  //   expect(controller).toBeDefined();
  // });

  it('should create a category', () => {
    expect(controller).toBeDefined();
  });

  it('should update a category', () => {
    expect(controller).toBeDefined();
  });

  it('should delete a category', () => {
    expect(controller).toBeDefined();
  });

  it('should get a category', () => {
    expect(controller).toBeDefined();
  });

  it('should list categories', () => {
    expect(controller).toBeDefined();
  });
});
